# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-16 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infotor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='percorso',
            options={'verbose_name_plural': 'Percorsi'},
        ),
        migrations.AlterModelOptions(
            name='torrente',
            options={'verbose_name_plural': 'Torrenti'},
        ),
        migrations.RemoveField(
            model_name='percorso',
            name='Operatiore',
        ),
        migrations.AddField(
            model_name='percorso',
            name='Operatore',
            field=models.CharField(default='', max_length=80, verbose_name='Ente manutentore'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='percorso',
            name='Arcitett',
            field=models.CharField(max_length=2, verbose_name='Interesse architettonico'),
        ),
        migrations.AlterField(
            model_name='percorso',
            name='CodReg',
            field=models.CharField(max_length=12, verbose_name='Codice catasto regionale'),
        ),
        migrations.AlterField(
            model_name='percorso',
            name='Dataril',
            field=models.DateField(verbose_name='Data aggiornamento'),
        ),
        migrations.AlterField(
            model_name='percorso',
            name='Denomi',
            field=models.CharField(max_length=80, verbose_name='Descrizione'),
        ),
        migrations.AlterField(
            model_name='percorso',
            name='Link',
            field=models.CharField(max_length=16, verbose_name='Link CMS'),
        ),
        migrations.AlterField(
            model_name='percorso',
            name='Natural',
            field=models.CharField(max_length=2, verbose_name='Interesse naturalistico'),
        ),
        migrations.AlterField(
            model_name='percorso',
            name='Nume',
            field=models.CharField(max_length=6, verbose_name='Numero percorso'),
        ),
        migrations.AlterField(
            model_name='percorso',
            name='Paesagg',
            field=models.CharField(max_length=2, verbose_name='Interesse paesaggistico'),
        ),
        migrations.AlterField(
            model_name='percorso',
            name='Pendenza',
            field=models.IntegerField(verbose_name='Pendenza'),
        ),
        migrations.AlterField(
            model_name='percorso',
            name='PerDif',
            field=models.CharField(max_length=3, verbose_name='Grado di difficoltà'),
        ),
        migrations.AlterField(
            model_name='percorso',
            name='PerLun',
            field=models.IntegerField(verbose_name='Lunghezza piana'),
        ),
        migrations.AlterField(
            model_name='percorso',
            name='PerLunF',
            field=models.IntegerField(verbose_name='Lunghezza inclinata'),
        ),
        migrations.AlterField(
            model_name='percorso',
            name='PerTem1',
            field=models.IntegerField(verbose_name='Tempo di percorrenza andata'),
        ),
        migrations.AlterField(
            model_name='percorso',
            name='PerTem2',
            field=models.IntegerField(verbose_name='Tempo di percorrenza ritorno'),
        ),
        migrations.AlterField(
            model_name='percorso',
            name='Percorr',
            field=models.CharField(max_length=2, verbose_name='Percorribilità'),
        ),
        migrations.AlterField(
            model_name='percorso',
            name='Perquo1',
            field=models.IntegerField(verbose_name='Quota inizio'),
        ),
        migrations.AlterField(
            model_name='percorso',
            name='Perquo2',
            field=models.IntegerField(verbose_name='Quota fine'),
        ),
        migrations.AlterField(
            model_name='percorso',
            name='ReteReg',
            field=models.CharField(max_length=4, verbose_name='Rete regionale'),
        ),
        migrations.AlterField(
            model_name='percorso',
            name='Segni',
            field=models.CharField(max_length=3, verbose_name='Segnaletica orizzontale'),
        ),
        migrations.AlterField(
            model_name='percorso',
            name='Storico',
            field=models.CharField(max_length=2, verbose_name='Interesse storico'),
        ),
        migrations.AlterField(
            model_name='percorso',
            name='Trek1',
            field=models.CharField(max_length=80, verbose_name='Nome/sigla/logo trekking'),
        ),
        migrations.AlterField(
            model_name='percorso',
            name='UTENTE',
            field=models.CharField(max_length=16, verbose_name='Utente aggiornatore'),
        ),
        migrations.AlterField(
            model_name='torrente',
            name='Caratter',
            field=models.CharField(max_length=2, verbose_name='Caratteristica'),
        ),
        migrations.AlterField(
            model_name='torrente',
            name='Comune',
            field=models.CharField(max_length=6, verbose_name='Comune'),
        ),
        migrations.AlterField(
            model_name='torrente',
            name='Dataril',
            field=models.DateField(verbose_name='Data aggiornamento'),
        ),
        migrations.AlterField(
            model_name='torrente',
            name='Grumon',
            field=models.CharField(max_length=11, verbose_name='Gruppo montuoso'),
        ),
        migrations.AlterField(
            model_name='torrente',
            name='Nuovo',
            field=models.CharField(max_length=2, verbose_name='Nuovo tracciato?'),
        ),
        migrations.AlterField(
            model_name='torrente',
            name='Pendenza',
            field=models.IntegerField(verbose_name='Pendenza'),
        ),
        migrations.AlterField(
            model_name='torrente',
            name='PerDif',
            field=models.CharField(max_length=3, verbose_name='Gradi di difficoltà'),
        ),
        migrations.AlterField(
            model_name='torrente',
            name='PerLun',
            field=models.IntegerField(verbose_name='Lunghezza piana'),
        ),
        migrations.AlterField(
            model_name='torrente',
            name='PerLunF',
            field=models.IntegerField(verbose_name='Lunghezza inclinata'),
        ),
        migrations.AlterField(
            model_name='torrente',
            name='PerTem1',
            field=models.IntegerField(verbose_name='Tempo di percorrenza andata'),
        ),
        migrations.AlterField(
            model_name='torrente',
            name='PerTem2',
            field=models.IntegerField(verbose_name='Tempo di percorrenza ritorno'),
        ),
        migrations.AlterField(
            model_name='torrente',
            name='Perquo1',
            field=models.IntegerField(verbose_name='Quota inizio'),
        ),
        migrations.AlterField(
            model_name='torrente',
            name='Perquo2',
            field=models.IntegerField(verbose_name='Quota fine'),
        ),
        migrations.AlterField(
            model_name='torrente',
            name='Provincia',
            field=models.CharField(max_length=2, verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='torrente',
            name='Regione',
            field=models.CharField(max_length=2, verbose_name='Regione'),
        ),
        migrations.AlterField(
            model_name='torrente',
            name='Rilevatore',
            field=models.CharField(max_length=50, verbose_name='Nome rilevatore'),
        ),
        migrations.AlterField(
            model_name='torrente',
            name='Sezion',
            field=models.CharField(max_length=7, verbose_name='Sezione'),
        ),
        migrations.AlterField(
            model_name='torrente',
            name='TipoRIL',
            field=models.CharField(max_length=3, verbose_name='Classe di accuratezza'),
        ),
        migrations.AlterField(
            model_name='torrente',
            name='Tipologia',
            field=models.CharField(max_length=2, verbose_name='Tipologia'),
        ),
        migrations.AlterField(
            model_name='torrente',
            name='Trtname',
            field=models.CharField(max_length=16, verbose_name='Nome tratta'),
        ),
    ]
